// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>FT_HTML_Script</b><br>
 * Generated     : <b>2022/05/11 3:42:02 pm</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  May 11, 2022
 * @author shalinib
 */
public abstract class FT_HTML_ScriptHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * orderinfoShipisbilltrue: with default state.
	 *		.id : orderinfo:shipisbill
	 * 		.type : checkbox
	 * 		.value : true
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : orderinfo:shipisbill
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_orderinfoShipisbilltr() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_orderinfoShipisbilltr"));
	}
	/**
	 * orderinfoShipisbilltrue: with specific test context and state.
	 *		.id : orderinfo:shipisbill
	 * 		.type : checkbox
	 * 		.value : true
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : orderinfo:shipisbill
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_orderinfoShipisbilltr(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_orderinfoShipisbilltr"), anchor, flags);
	}
	
	/**
	 * PlantsByWebSphereLogin: with default state.
	 *		.title : Plants By WebSphere Login
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://10.134.59.146:9443/PlantsByWebSphere/cart.jsf
	 */
	protected DocumentTestObject document_plantsByWebSphereLogi() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_plantsByWebSphereLogi"));
	}
	/**
	 * PlantsByWebSphereLogin: with specific test context and state.
	 *		.title : Plants By WebSphere Login
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://10.134.59.146:9443/PlantsByWebSphere/cart.jsf
	 */
	protected DocumentTestObject document_plantsByWebSphereLogi(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_plantsByWebSphereLogi"), anchor, flags);
	}
	
	/**
	 * PlantsByWebSphereOrderInfo: with default state.
	 *		.title : Plants By WebSphere Order Info
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://10.134.59.146:9443/PlantsByWebSphere/login.jsf
	 */
	protected DocumentTestObject document_plantsByWebSphereOrde() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_plantsByWebSphereOrde"));
	}
	/**
	 * PlantsByWebSphereOrderInfo: with specific test context and state.
	 *		.title : Plants By WebSphere Order Info
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://10.134.59.146:9443/PlantsByWebSphere/login.jsf
	 */
	protected DocumentTestObject document_plantsByWebSphereOrde(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_plantsByWebSphereOrde"), anchor, flags);
	}
	
	/**
	 * PlantsByWebSphereOrderDone: with default state.
	 *		.title : Plants By WebSphere Order Done
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://10.134.59.146:9443/PlantsByWebSphere/checkout_final.jsf
	 */
	protected DocumentTestObject document_plantsByWebSphereOrde2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_plantsByWebSphereOrde2"));
	}
	/**
	 * PlantsByWebSphereOrderDone: with specific test context and state.
	 *		.title : Plants By WebSphere Order Done
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://10.134.59.146:9443/PlantsByWebSphere/checkout_final.jsf
	 */
	protected DocumentTestObject document_plantsByWebSphereOrde2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_plantsByWebSphereOrde2"), anchor, flags);
	}
	
	/**
	 * PlantsByWebSphereProductDetail: with default state.
	 *		.title : Plants By WebSphere Product Detail
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://10.134.59.146:9443/PlantsByWebSphere/promo.jsf
	 */
	protected DocumentTestObject document_plantsByWebSphereProd() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_plantsByWebSphereProd"));
	}
	/**
	 * PlantsByWebSphereProductDetail: with specific test context and state.
	 *		.title : Plants By WebSphere Product Detail
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://10.134.59.146:9443/PlantsByWebSphere/promo.jsf
	 */
	protected DocumentTestObject document_plantsByWebSphereProd(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_plantsByWebSphereProd"), anchor, flags);
	}
	
	/**
	 * AddToCart: with default state.
	 *		.alt : Add to Cart
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_add_to_ ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_addToCart() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_addToCart"));
	}
	/**
	 * AddToCart: with specific test context and state.
	 *		.alt : Add to Cart
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_add_to_ ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_addToCart(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_addToCart"), anchor, flags);
	}
	
	/**
	 * AddToCart: with default state.
	 *		.alt : Add to Cart
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_add_to_ ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_addToCart2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_addToCart2"));
	}
	/**
	 * AddToCart: with specific test context and state.
	 *		.alt : Add to Cart
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_add_to_ ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_addToCart2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_addToCart2"), anchor, flags);
	}
	
	/**
	 * BonsaiTree: with default state.
	 *		.alt : Bonsai Tree
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/trees_bonsai_4 ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_bonsaiTree() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_bonsaiTree"));
	}
	/**
	 * BonsaiTree: with specific test context and state.
	 *		.alt : Bonsai Tree
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/trees_bonsai_4 ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_bonsaiTree(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_bonsaiTree"), anchor, flags);
	}
	
	/**
	 * CheckoutNow: with default state.
	 *		.alt : Checkout Now
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_checkou ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_checkoutNow() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_checkoutNow"));
	}
	/**
	 * CheckoutNow: with specific test context and state.
	 *		.alt : Checkout Now
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_checkou ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_checkoutNow(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_checkoutNow"), anchor, flags);
	}
	
	/**
	 * CheckoutNow: with default state.
	 *		.alt : Checkout Now
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_submit_ ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_checkoutNow2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_checkoutNow2"));
	}
	/**
	 * CheckoutNow: with specific test context and state.
	 *		.alt : Checkout Now
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_submit_ ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_checkoutNow2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_checkoutNow2"), anchor, flags);
	}
	
	/**
	 * Coleus: with default state.
	 *		.alt : Coleus
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/servlet/ImageServlet?action=getimag ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_coleus() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_coleus"));
	}
	/**
	 * Coleus: with specific test context and state.
	 *		.alt : Coleus
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/servlet/ImageServlet?action=getimag ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_coleus(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_coleus"), anchor, flags);
	}
	
	/**
	 * Continue: with default state.
	 *		.alt : Continue
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_continu ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_continue() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_continue"));
	}
	/**
	 * Continue: with specific test context and state.
	 *		.alt : Continue
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_continu ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_continue(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_continue"), anchor, flags);
	}
	
	/**
	 * ContinueShopping: with default state.
	 *		.alt : Continue Shopping
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_continu ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_continueShopping() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_continueShopping"));
	}
	/**
	 * ContinueShopping: with specific test context and state.
	 *		.alt : Continue Shopping
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_continu ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_continueShopping(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_continueShopping"), anchor, flags);
	}
	
	/**
	 * Impatiens: with default state.
	 *		.alt : Impatiens
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/servlet/ImageServlet?action=getimag ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_impatiens() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_impatiens"));
	}
	/**
	 * Impatiens: with specific test context and state.
	 *		.alt : Impatiens
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/servlet/ImageServlet?action=getimag ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_impatiens(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_impatiens"), anchor, flags);
	}
	
	/**
	 * SignIn: with default state.
	 *		.alt : Sign in
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_sign_in ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_signIn() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_signIn"));
	}
	/**
	 * SignIn: with specific test context and state.
	 *		.alt : Sign in
	 * 		.id : 
	 * 		.src : https://10.134.59.146:9443/PlantsByWebSphere/javax.faces.resource/button_sign_in ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_signIn(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_signIn"), anchor, flags);
	}
	
	/**
	 * loginEmail: with default state.
	 *		.id : login:email
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : login:email
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_loginEmail() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_loginEmail"));
	}
	/**
	 * loginEmail: with specific test context and state.
	 *		.id : login:email
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : login:email
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_loginEmail(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_loginEmail"), anchor, flags);
	}
	
	/**
	 * loginPassword: with default state.
	 *		.id : login:password
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : login:password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_loginPassword() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_loginPassword"));
	}
	/**
	 * loginPassword: with specific test context and state.
	 *		.id : login:password
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : login:password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_loginPassword(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_loginPassword"), anchor, flags);
	}
	
	/**
	 * orderinfoCcardnum: with default state.
	 *		.id : orderinfo:ccardnum
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : orderinfo:ccardnum
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_orderinfoCcardnum() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_orderinfoCcardnum"));
	}
	/**
	 * orderinfoCcardnum: with specific test context and state.
	 *		.id : orderinfo:ccardnum
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : orderinfo:ccardnum
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_orderinfoCcardnum(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_orderinfoCcardnum"), anchor, flags);
	}
	
	/**
	 * orderinfoCcholdername: with default state.
	 *		.id : orderinfo:ccholdername
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : orderinfo:ccholdername
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_orderinfoCcholdername() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_orderinfoCcholdername"));
	}
	/**
	 * orderinfoCcholdername: with specific test context and state.
	 *		.id : orderinfo:ccholdername
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : orderinfo:ccholdername
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_orderinfoCcholdername(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_orderinfoCcholdername"), anchor, flags);
	}
	
	/**
	 * productQuantity: with default state.
	 *		.id : product:quantity
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : product:quantity
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_productQuantity() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_productQuantity"));
	}
	/**
	 * productQuantity: with specific test context and state.
	 *		.id : product:quantity
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : product:quantity
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_productQuantity(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_productQuantity"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point Impatiens_Impatiens object in the SUT.
	 */
	protected IFtVerificationPoint Impatiens_ImpatiensVP() 
	{
		return vp("Impatiens_Impatiens");
	}
	protected IFtVerificationPoint Impatiens_ImpatiensVP(TestObject anchor)
	{
		return vp("Impatiens_Impatiens", anchor);
	}
	
	/**
	 * Locate and return the verification point productQuantity_text object in the SUT.
	 */
	protected IFtVerificationPoint productQuantity_textVP() 
	{
		return vp("productQuantity_text");
	}
	protected IFtVerificationPoint productQuantity_textVP(TestObject anchor)
	{
		return vp("productQuantity_text", anchor);
	}
	
	

	protected FT_HTML_ScriptHelper()
	{
		setScriptName("FT_HTML_Script");
	}
	
}

